In [10]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.DataFrame({
    'Age': [25, 30, 35, 40],
    'Color': ['Red', 'Blue', 'Green', 'Red'],
    'Target': [0, 1, 0, 1]
})

df

   Age  Color  Target
0   25    Red       0
1   30   Blue       1
2   35  Green       0
3   40    Red       1

In [3]:
X = df[['Age', 'Color']]
y = df['Target']

### One-Hot Encoding (ohe)

In [5]:
# One-hot encode categorical feature (drop one column)
encoder = OneHotEncoder(drop='first', sparse_output=False)
X_cat = encoder.fit_transform(X[['Color']])
X_cat

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

In [6]:
# Combine with numerical features
X_encoded = pd.concat(
    [X[['Age']].reset_index(drop=True),
     pd.DataFrame(X_cat, columns=encoder.get_feature_names_out())],
    axis=1
)

X_encoded

   Age  Color_Green  Color_Red
0   25          0.0        1.0
1   30          0.0        0.0
2   35          1.0        0.0
3   40          0.0        1.0

### Ordinal Encoding

In [8]:
df = pd.DataFrame({
    'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'Bachelor']
})

df

     Education
0  High School
1     Bachelor
2       Master
3          PhD
4     Bachelor

In [12]:
education_order = ['High School', 'Bachelor', 'Master', 'PhD']

encoder = OrdinalEncoder(categories=[education_order])
df['Education_encoded'] = encoder.fit_transform(df[['Education']])
print("\nOrdinal Encoded Data:")
df

Ordinal Encoded Data:

     Education  Education_encoded
0  High School                0.0
1     Bachelor                1.0
2       Master                2.0
3          PhD                3.0
4     Bachelor                1.0